spring.application.name=base



# PostgreSQL Connection Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/authentication
spring.datasource.username=postgres
spring.datasource.password=admin
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA/Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true               

# Config jwt
jwt.base64-secret=TDztjuiGG+/hJplhARIzotz+eTCq7QpHz1XNN1g5QlaA41Ack3ybKFp/fbs5LLdH5zX+/WKIh6/1Z7jEJn2umA==
jwt.token-expiration-in-seconds=900
jwt.algorithm=HS512



# CORS configuration
spring.cors.allowed-origins=http://localhost:3000
spring.cors.allowed-methods=GET,POST,PUT,DELETE,OPTIONS
spring.cors.allowed-headers=*
spring.cors.allow-credentials=true

# Redis configuration
spring.cache.type=redis
spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.cache.redis.key-prefix=custom-prefix
spring.cache.redis.time-to-live=60000
spring.cache.redis.maxmemory=128mb

#Swagger
